
import Head from 'next/head'
import Login from './app/pages/login/login'
import Noticies from '../pages/app/pages/policies/Notices'
import Policies from './app/pages/policies/Policies'
import Terms from './app/pages/policies/Terms'
import Proyect from './app/pages/Proyectos/Proyect'
import styles from '../styles/Home.module.css'
import Recursos from './recursos'
import NewProyect from './newProyect'
import MenuPrincipal from './app/pages/customProyects/MenuPrincipal'
import Costos from './costos'
import DetalleDeProyecto from './detalleDeProyecto'
import EditarProyecto from './editarProyecto'
import Splash from './app/components/splash'
import CustomNavbar from './app/components/CustomNavbar'
import apiPrueba from '../api/hola'
import ViewProyect from './viewProyect'


const Home=()=> {
  return (
    <div>
      <Head>
        <title>Calculadora Lunave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
     
      
        <div>
        
        <Login/>
            

        </div>
      
          
  </div>
  )
  }


  export const getStaticProps= async (ctx) => {
    
    const {data} = await apiPrueba.get('?name=cami&edad=1')
  console.log("response service: ",JSON.stringify(data))
   return{
    props: {
    
    }
   }
  }

export default Home;

